AWSTemplateFormatVersion: '2010-09-09'
Description: >-
   Project Carnation : CFN Template to create am IAM Role for Lambda Function and State Machine

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Carnation
  Modification History:
    - 1.0.0  - April 18, 2023   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyId
    #################################### Lambda Function ###########################################
    - Label:
        default: "Service Names:"
      Parameters:
      - LambdaFunctionNameOne
      - LambdaFunctionNameTwo
      - LambdaExecutionRoleName
      - LambdaExecutionPolicyName
    #################################### DynamoDB Table ############################################
    - Label: 
        default: "DynamoDB Configuration:"
      Parameters: 
      - DynamoDBTableName
    #################################### SNS Topic #################################################
    - Label: 
        default: "SNS Topic:"
      Parameters: 
        - SNSTopicBaseName
    #################################### SQS Queue #################################################
    - Label: 
        default: "SQS Queue:"
      Parameters: 
        - SQSQueueBaseName
    #################################### Step Function #############################################
    - Label:
        default: "Step Function:"
      Parameters:
      - StepFunctionExecutionRoleName
    #   - StepFunctionExecutionPolicyName
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## Lambda Function ###########################################
      LambdaFunctionNameOne: 
        default: "Processing Lammba Function Name."
      LambdaFunctionNameTwo: 
        default: "Processing Lammba Function Name."
      LambdaExecutionRoleName: 
        default: "Lambda Function Execution Role Name."
      LambdaExecutionPolicyName:
        default: "Lambda Function Execution Policy Name."
      ################################## DynamoDB Table ############################################
      DynamoDBTableName: 
        default: "DynamoDB Table."
      ################################## SNS Topic With Email Subscription #########################
      SNSTopicBaseName:
        default: "SNS Topic."
      #################################### SQS Queue #################################################
      SQSQueueBaseName:
        default: "SQS Queue."
      ################################## Step Function #############################################
      StepFunctionExecutionRoleName: 
        default: "Step Function Execution Role Name."
      StepFunctionExecutionPolicyName: 
        default: "Step Function Execution Policy Name."
      # StepFunctionName: 
      #   default: "The Name Of The Step Function"
Parameters:
  ################## Project Name and Environment ###############################################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ##################################### Lambda Function ###########################################
  LambdaFunctionNameOne:
    Default: some-lambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaFunctionNameTwo:
    Default: some-other-ambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionRoleName:
    Default: Lambda-Function-Role-Name
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionPolicyName:
    Default: Lambda-Function-Policy-Name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  ###################################### DynamoDB Table ############################################
  DynamoDBTableName:
    Default: carnation-table
    Description: "The Name Of The Dynamodb Table Used For Iterating Using Step Function Map State."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "carnation-sns-topic"
    Description: "The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ###################################### SQS Queue #################################################
  SQSQueueBaseName:
    Default: "some-sqs-queue"
    Description: "The Base Name Of The Sqs Queue (Dead Letter Quque). The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ########################################### State Machine #############################################
  StepFunctionExecutionRoleName:
    Default: Step-Function-Role-Name
    Description: Step Function Execution Role Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  StepFunctionExecutionPolicyName:
    Default: Step-Function-Policy-Name
    Description: Step Function Execution Policy Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  # StepFunctionName:
  #   Default: step-function-name
  #   Description: Step Function Execution Policy Name
  #   Type: String
  #   MinLength: 5
  #   MaxLength: 50
  #   AllowedPattern: "[a-zA-Z-]*"
  #   ConstraintDescription: The length should be between 5 and 50, must contain only lowecase letters, numbers and hyphen (-).
Resources:

  #################################### Lambda Execution Role ##########################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Ref LambdaExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionNameOne}-${Environment}-${AWS::Region}:*'
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionNameTwo}-${Environment}-${AWS::Region}:*'
            - Sid: AllowDynamoDBPutAndGetItem
              Effect: Allow
              Action: 
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !Sub 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}-${Environment}-${AWS::Region}'
            - Sid: AllowSNSPublishMessage
              Effect: Allow
              Action: 
                - sns:Publish
              Resource: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
            - Sid: AllowSQSReadWriteDelete
              Effect: Allow
              Action: 
                - sqs:ReceiveMessage
                - sqs:SendMessage
                - sqs:DeleteMessage
              Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueBaseName}-${Environment}-${AWS::Region}'
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment

  ################################ State Machine Execution Role #################################
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref StepFunctionExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
      Policies:
        - PolicyName: !Ref StepFunctionExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowKMSEncryptDecrypt
              Effect: Allow
              Action: 
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyPair
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
            - Sid: AllowKSQSSendMessage
              Effect: Allow
              Action: 
              - sqs:SendMessage
              - sqs:PurgeQueue
              Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueBaseName}-${Environment}-${AWS::Region}'
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
  StepFunctionExecutionRoleArn:
    Description: The Arn of the Step Function Execution Role
    Value: !GetAtt StepFunctionExecutionRole.Arn
